---
- name: Reverting the route to default state
  hosts: localhost

  tasks:
  - name: updating the route
    kubernetes.core.k8s:
      state: present
      definition:
        apiVersion: route.openshift.io/v1
        kind: Route
        metadata:
          name: frontend
          namespace: "{{ namespace }}"
        spec:
          host: frontend-carinfo.apps.cluster-tt95s.tt95s.sandbox186.opentlc.com
          port:
            targetPort: 8080
          tls:
            termination: edge
          to:
            kind: Service
            name: "frontend-{{ old_version }}"
            weight: 100
          wildcardPolicy: None